chassis_controller:
  ros__parameters:
    # =========================================
    # 1. 话题配置 (EtherCAT Topic 映射)
    #    App1=RC, App2=Drive, App3=Steer
    #    请务必替换 snXXXXXX 为实际序列号
    # =========================================
    topic_rc_read: '/ecat/sn4587585/app1/read'
    topic_drive_write: '/ecat/sn4587586/app1/write'
    topic_steer_read: '/ecat/sn4587586/app2/read'
    topic_steer_write: '/ecat/sn4587586/app2/write'
    topic_yaw_read: "/ecat/sn4587586/app3/read" # 读取 Yaw 电机编码器确定车头朝向

    # =========================================
    # 2. 几何参数 (单位: 米)
    # =========================================
    wheel_track: 0.372  # 轮距 (左右轮中心的距离 / Width)
    wheel_base: 0.372   # 轴距 (前后轮中心的距离 / Length)

    # =========================================
    # 3. 电机零位设置 (ECD值 0-8191)
    #    对应: FL(前左), FR(前右), BL(后左), BR(后右)
    # =========================================
    offset_fl: 7411
    offset_fr: 7530
    offset_bl: 3419
    offset_br: 2051

gimbal_controller:
  ros__parameters:
    mouse_sensitivity: 1.0
    
    # Topics
    topic_rc_read: "/ecat/sn4587585/app1/read"
    topic_imu_read: "/ecat/sn4587585/app2/read"
    
    # Pitch (DJI Motor)
    topic_pitch_write: "/ecat/sn4587585/app4/write"
    topic_pitch_read: "/ecat/sn4587585/app4/read"
    
    # Yaw (LK Motor)
    topic_yaw_write: "/ecat/sn4587586/app3/write"
    topic_yaw_read: "/ecat/sn4587586/app3/read"

    # Limits & Offsets
    pitch_center_ecd: 4540
    pitch_min_deg: -25.0
    pitch_max_deg: 40.0

# Yaw Cascade PID Params
    # Position Loop (Output: Target Angular Velocity in rad/s)
    yaw_pos_kp: 15.0
    yaw_pos_ki: 0.2
    yaw_pos_kd: 0.2
    yaw_pos_max_out: 30.0   # 新增: 最大输出角速度
    yaw_pos_max_iout: 30.0   # 新增: 积分限幅

    # Speed Loop (Output: Torque Current)
    yaw_spd_kp: 220.0
    yaw_spd_ki: 0.5
    yaw_spd_kd: 2000.0
    yaw_spd_max_out: 2048.0 # 新增: 最大力矩电流
    yaw_spd_max_iout: 200.0 # 新增: 积分限幅
