# Auto-generated by ros2_systemd_manager.py
# Re-generate with: make update

PYTHON ?= python3
SUDO ?= sudo
SCRIPT ?= /home/infantry/infantry_ws/scripts/ros2_systemd_manager/ros2_systemd_manager.py
CONFIG ?= /home/infantry/infantry_ws/scripts/ros2_systemd_manager/ros2_services.yaml
WORKSPACE_KEY := infantry_ws
UNITS := ros2-foxglove-bridge.service ros2-soem-bringup.service ros2-infantry-chassis.service ros2-dji-referee.service ros2-sp-vision-autoaim.service

EFFECTIVE_SCRIPT := $(if $(strip $(SCRIPT)),$(SCRIPT),/home/infantry/infantry_ws/scripts/ros2_systemd_manager/ros2_systemd_manager.py)
EFFECTIVE_CONFIG := $(if $(strip $(CONFIG)),$(CONFIG),/home/infantry/infantry_ws/scripts/ros2_systemd_manager/ros2_services.yaml)

.PHONY: help install-only install-start-enable uninstall start stop restart status enable disable logs logs-follow update update-makefile start-ros2-foxglove-bridge stop-ros2-foxglove-bridge restart-ros2-foxglove-bridge status-ros2-foxglove-bridge enable-ros2-foxglove-bridge disable-ros2-foxglove-bridge logs-ros2-foxglove-bridge start-ros2-soem-bringup stop-ros2-soem-bringup restart-ros2-soem-bringup status-ros2-soem-bringup enable-ros2-soem-bringup disable-ros2-soem-bringup logs-ros2-soem-bringup start-ros2-infantry-chassis stop-ros2-infantry-chassis restart-ros2-infantry-chassis status-ros2-infantry-chassis enable-ros2-infantry-chassis disable-ros2-infantry-chassis logs-ros2-infantry-chassis start-ros2-dji-referee stop-ros2-dji-referee restart-ros2-dji-referee status-ros2-dji-referee enable-ros2-dji-referee disable-ros2-dji-referee logs-ros2-dji-referee start-ros2-sp-vision-autoaim stop-ros2-sp-vision-autoaim restart-ros2-sp-vision-autoaim status-ros2-sp-vision-autoaim enable-ros2-sp-vision-autoaim disable-ros2-sp-vision-autoaim logs-ros2-sp-vision-autoaim

help:
	@echo "Targets:"
	@echo "  make install-only           # install unit files only"
	@echo "  make install-start-enable   # install + start + enable"
	@echo "  make start                  # systemctl start all configured units"
	@echo "  make stop                   # systemctl stop all configured units"
	@echo "  make restart                # systemctl restart all configured units"
	@echo "  make status                 # systemctl status all configured units"
	@echo "  make enable                 # systemctl enable all configured units"
	@echo "  make disable                # systemctl disable all configured units"
	@echo "  make logs                   # show last 200 log lines for all configured units"
	@echo "  make logs-follow            # follow logs for all configured units"
	@echo "  make <op>-<service>         # op in start/stop/restart/status/enable/disable/logs"
	@echo "  make uninstall              # uninstall all configured units"
	@echo "  make update                 # full update: install/start/enable + refresh Makefile"
	@echo "  make update-makefile        # refresh Makefile only (no systemd changes)"

install-only:
	$(SUDO) $(PYTHON) "$(EFFECTIVE_SCRIPT)" install-only --config "$(EFFECTIVE_CONFIG)" --workspace-key "$(WORKSPACE_KEY)"

install-start-enable:
	$(SUDO) $(PYTHON) "$(EFFECTIVE_SCRIPT)" install-start-enable --config "$(EFFECTIVE_CONFIG)" --workspace-key "$(WORKSPACE_KEY)"

uninstall:
	$(SUDO) $(PYTHON) "$(EFFECTIVE_SCRIPT)" uninstall --config "$(EFFECTIVE_CONFIG)" --workspace-key "$(WORKSPACE_KEY)"

start:
	$(SUDO) systemctl start $(UNITS)

stop:
	$(SUDO) systemctl stop $(UNITS)

restart:
	$(SUDO) systemctl restart $(UNITS)

status:
	$(SUDO) systemctl status $(UNITS)

enable:
	$(SUDO) systemctl enable $(UNITS)

disable:
	$(SUDO) systemctl disable $(UNITS)

logs:
	$(SUDO) journalctl $(foreach u,$(UNITS),-u $(u)) -n 200 --no-pager

logs-follow:
	$(SUDO) journalctl $(foreach u,$(UNITS),-u $(u)) -f

update:
	$(SUDO) $(PYTHON) "$(EFFECTIVE_SCRIPT)" install-start-enable --config "$(EFFECTIVE_CONFIG)" --workspace-key "$(WORKSPACE_KEY)"

update-makefile:
	$(PYTHON) "$(EFFECTIVE_SCRIPT)" update-makefile --config "$(EFFECTIVE_CONFIG)" --workspace-key "$(WORKSPACE_KEY)"


start-ros2-foxglove-bridge:
	$(SUDO) systemctl start "ros2-foxglove-bridge.service"

stop-ros2-foxglove-bridge:
	$(SUDO) systemctl stop "ros2-foxglove-bridge.service"

restart-ros2-foxglove-bridge:
	$(SUDO) systemctl restart "ros2-foxglove-bridge.service"

status-ros2-foxglove-bridge:
	$(SUDO) systemctl status "ros2-foxglove-bridge.service"

enable-ros2-foxglove-bridge:
	$(SUDO) systemctl enable "ros2-foxglove-bridge.service"

disable-ros2-foxglove-bridge:
	$(SUDO) systemctl disable "ros2-foxglove-bridge.service"

logs-ros2-foxglove-bridge:
	$(SUDO) journalctl -u "ros2-foxglove-bridge.service" -n 200 --no-pager


start-ros2-soem-bringup:
	$(SUDO) systemctl start "ros2-soem-bringup.service"

stop-ros2-soem-bringup:
	$(SUDO) systemctl stop "ros2-soem-bringup.service"

restart-ros2-soem-bringup:
	$(SUDO) systemctl restart "ros2-soem-bringup.service"

status-ros2-soem-bringup:
	$(SUDO) systemctl status "ros2-soem-bringup.service"

enable-ros2-soem-bringup:
	$(SUDO) systemctl enable "ros2-soem-bringup.service"

disable-ros2-soem-bringup:
	$(SUDO) systemctl disable "ros2-soem-bringup.service"

logs-ros2-soem-bringup:
	$(SUDO) journalctl -u "ros2-soem-bringup.service" -n 200 --no-pager


start-ros2-infantry-chassis:
	$(SUDO) systemctl start "ros2-infantry-chassis.service"

stop-ros2-infantry-chassis:
	$(SUDO) systemctl stop "ros2-infantry-chassis.service"

restart-ros2-infantry-chassis:
	$(SUDO) systemctl restart "ros2-infantry-chassis.service"

status-ros2-infantry-chassis:
	$(SUDO) systemctl status "ros2-infantry-chassis.service"

enable-ros2-infantry-chassis:
	$(SUDO) systemctl enable "ros2-infantry-chassis.service"

disable-ros2-infantry-chassis:
	$(SUDO) systemctl disable "ros2-infantry-chassis.service"

logs-ros2-infantry-chassis:
	$(SUDO) journalctl -u "ros2-infantry-chassis.service" -n 200 --no-pager


start-ros2-dji-referee:
	$(SUDO) systemctl start "ros2-dji-referee.service"

stop-ros2-dji-referee:
	$(SUDO) systemctl stop "ros2-dji-referee.service"

restart-ros2-dji-referee:
	$(SUDO) systemctl restart "ros2-dji-referee.service"

status-ros2-dji-referee:
	$(SUDO) systemctl status "ros2-dji-referee.service"

enable-ros2-dji-referee:
	$(SUDO) systemctl enable "ros2-dji-referee.service"

disable-ros2-dji-referee:
	$(SUDO) systemctl disable "ros2-dji-referee.service"

logs-ros2-dji-referee:
	$(SUDO) journalctl -u "ros2-dji-referee.service" -n 200 --no-pager


start-ros2-sp-vision-autoaim:
	$(SUDO) systemctl start "ros2-sp-vision-autoaim.service"

stop-ros2-sp-vision-autoaim:
	$(SUDO) systemctl stop "ros2-sp-vision-autoaim.service"

restart-ros2-sp-vision-autoaim:
	$(SUDO) systemctl restart "ros2-sp-vision-autoaim.service"

status-ros2-sp-vision-autoaim:
	$(SUDO) systemctl status "ros2-sp-vision-autoaim.service"

enable-ros2-sp-vision-autoaim:
	$(SUDO) systemctl enable "ros2-sp-vision-autoaim.service"

disable-ros2-sp-vision-autoaim:
	$(SUDO) systemctl disable "ros2-sp-vision-autoaim.service"

logs-ros2-sp-vision-autoaim:
	$(SUDO) journalctl -u "ros2-sp-vision-autoaim.service" -n 200 --no-pager
