slaves:
  - sn4653115:
      sdo_len: !uint16_t 150
      task_count: !uint8_t 4
      latency_pub_topic: !std::string '/ecat/sn4653115/latency'

      tasks:
        - app_1:
            sdowrite_task_type: !uint8_t 1
            conf_connection_lost_read_action: !uint8_t 0x02
            pub_topic: !std::string '/ecat/sn4653115/app1/read'
            pdoread_offset: !uint16_t 0

        - app_2:
            sdowrite_task_type: !uint8_t 3
            conf_connection_lost_read_action: !uint8_t 0x01
            pub_topic: !std::string '/ecat/sn4653115/app2/read'
            pdoread_offset: !uint16_t 19
            sdowrite_can_inst: !uint8_t 2
            sdowrite_packet1_id: !uint32_t 0x01
            sdowrite_packet2_id: !uint32_t 0x02
            sdowrite_packet3_id: !uint32_t 0x03
            conf_frame_name: !std::string 'imu_link'

        - app_3:
            sdowrite_task_type: !uint8_t 5
            conf_connection_lost_read_action: !uint8_t 0x01
            sdowrite_connection_lost_write_action: !uint8_t 0x02
            pub_topic: !std::string '/ecat/sn4653115/app3/read'
            pdoread_offset: !uint16_t 40
            sub_topic: !std::string '/ecat/sn4653115/app3/write'
            pdowrite_offset: !uint16_t 0
            sdowrite_control_period: !uint16_t 1
            sdowrite_can_packet_id: !uint32_t 0x200
            sdowrite_motor1_can_id: !uint32_t 0x201
            sdowrite_motor2_can_id: !uint32_t 0x202
            sdowrite_motor3_can_id: !uint32_t 0x203
            sdowrite_motor4_can_id: !uint32_t 0
            sdowrite_can_inst: !uint8_t 1
            sdowrite_motor1_control_type: !uint8_t 2
            sdowrite_motor1_speed_pid_kp: !float 13.5
            sdowrite_motor1_speed_pid_ki: !float 1
            sdowrite_motor1_speed_pid_kd: !float 0
            sdowrite_motor1_speed_pid_max_out: !float 16384
            sdowrite_motor1_speed_pid_max_iout: !float 2000
            sdowrite_motor2_control_type: !uint8_t 2
            sdowrite_motor2_speed_pid_kp: !float 13.5
            sdowrite_motor2_speed_pid_ki: !float 1
            sdowrite_motor2_speed_pid_kd: !float 0
            sdowrite_motor2_speed_pid_max_out: !float 16384
            sdowrite_motor2_speed_pid_max_iout: !float 2000
            sdowrite_motor3_control_type: !uint8_t 1

        - app_4:
            sdowrite_task_type: !uint8_t 5
            conf_connection_lost_read_action: !uint8_t 0x01
            sdowrite_connection_lost_write_action: !uint8_t 0x02
            pub_topic: !std::string '/ecat/sn4653115/app4/read'
            pdoread_offset: !uint16_t 67
            sub_topic: !std::string '/ecat/sn4653115/app4/write'
            pdowrite_offset: !uint16_t 9
            sdowrite_control_period: !uint16_t 1
            sdowrite_can_packet_id: !uint32_t 0x1ff
            sdowrite_motor1_can_id: !uint32_t 0
            sdowrite_motor2_can_id: !uint32_t 0
            sdowrite_motor3_can_id: !uint32_t 0
            sdowrite_motor4_can_id: !uint32_t 0x208
            sdowrite_can_inst: !uint8_t 1
            sdowrite_motor4_control_type: !uint8_t 3
            sdowrite_motor4_speed_pid_kp: !float 65
            sdowrite_motor4_speed_pid_ki: !float 0.2
            sdowrite_motor4_speed_pid_kd: !float 0
            sdowrite_motor4_speed_pid_max_out: !float 25000
            sdowrite_motor4_speed_pid_max_iout: !float 3000
            sdowrite_motor4_angle_pid_kp: !float 1.5
            sdowrite_motor4_angle_pid_ki: !float 0
            sdowrite_motor4_angle_pid_kd: !float 10.5
            sdowrite_motor4_angle_pid_max_out: !float 1800
            sdowrite_motor4_angle_pid_max_iout: !float 0
  - sn4128829:
      sdo_len: !uint16_t 11
      task_count: !uint8_t 1
      latency_pub_topic: !std::string "/ecat/sn4128829/latency"

      tasks:
        - app_1:
            sdowrite_task_type: !uint8_t 2
            conf_connection_lost_read_action: !uint8_t 0x01
            sdowrite_connection_lost_write_action: !uint8_t 0x02
            pub_topic: !std::string "/ecat/sn4128829/app1/read"
            pdoread_offset: !uint16_t 0
            sub_topic: !std::string "/ecat/sn4128829/app1/write"
            pdowrite_offset: !uint16_t 0
            sdowrite_control_period: !uint16_t 1
            sdowrite_can_packet_id: !uint32_t 0x141
            sdowrite_can_inst: !uint8_t 1
            sdowrite_control_type: !uint8_t 2

  - sn2228292:
      sdo_len: !uint16_t 13
      task_count: !uint8_t 2
      latency_pub_topic: !std::string "/ecat/sn2228292/latency"

      tasks:
        - app_1:
            sdowrite_task_type: !uint8_t 2
            conf_connection_lost_read_action: !uint8_t 0x01
            sdowrite_connection_lost_write_action: !uint8_t 0x02
            pub_topic: !std::string "/ecat/sn2228292/app1/read"
            pdoread_offset: !uint16_t 0
            sub_topic: !std::string "/ecat/sn2228292/app1/write"
            pdowrite_offset: !uint16_t 0
            sdowrite_control_period: !uint16_t 1
            sdowrite_can_inst: !uint8_t 1
            sdowrite_control_type: !uint8_t 8

        - app_2:
            sdowrite_task_type: !uint8_t 2
            conf_connection_lost_read_action: !uint8_t 0x01
            sdowrite_connection_lost_write_action: !uint8_t 0x02
            pub_topic: !std::string "/ecat/sn2228292/app2/read"
            pdoread_offset: !uint16_t 32
            sub_topic: !std::string "/ecat/sn2228292/app2/write"
            pdowrite_offset: !uint16_t 8
            sdowrite_control_period: !uint16_t 1
            sdowrite_can_inst: !uint8_t 2
            sdowrite_control_type: !uint8_t 8
