<?xml version="1.0"?>
<package format="3">
  <name>sp_vision_launch</name>
  <version>0.1.0</version>
  <description>Launch package for SP Vision with symlinked configs</description>
  <maintainer email="infantry@example.com">infantry</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
